setTimeout(function() {
    $('.about-info-inner').typed({
      strings: [
        "<span>Hi, I am Sourav Das.</span> With over a year of experience in the LPG (liquefied petroleum gas) plant industry, I am now eager to transition my career path into the exciting fields of web development and cloud engineering. During my tenure at the LPG plant, I gained valuable insights into the intricacies of the industry, honing my technical skills and developing a keen eye for detail. However, as I delved deeper into the world of technology and witnessed the remarkable advancements in web development and cloud computing, I realized that my true passion lies in these dynamic and ever-evolving domains.<br><br>My journey in the LPG plant provided me with a strong foundation in problem-solving, teamwork, and project management. I cultivated a meticulous approach to my work, ensuring compliance with safety regulations, optimizing processes, and troubleshooting technical issues. While these skills have been invaluable, I yearn to explore my creativity and expand my knowledge in the field of web development. The endless possibilities of designing and building interactive websites and applications captivate me, and I am eager to contribute my problem-solving expertise to this innovative industry.<br><br>Additionally, the growing demand for cloud engineering professionals has caught my attention. The ability to harness the power of cloud technologies to optimize infrastructure, enhance scalability, and improve data security has become increasingly crucial in today's digital landscape. I am drawn to the challenge of mastering cloud platforms, such as AWS, and leveraging their capabilities to create efficient and robust systems.<br><br>In pursuit of my career switch, I am dedicated to acquiring the necessary skills and knowledge through self-study, online courses, and immersive bootcamps. I am excited to embark on this new journey, combining my previous experience in the LPG plant industry with my newfound passion for web development and cloud engineering. By blending my technical expertise with creative problem-solving, I aim to make a meaningful impact in the digital realm and contribute to the technological advancements shaping our world."
      ],
      typeSpeed: -10000,
      contentType: 'html'
    });
  }, 100);
